inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "test/**/*"
Metrics/ClassLength:
  Exclude:
    - "lib/google/cloud/env.rb"
Naming/FileName:
  Exclude:
    - "lib/google-cloud-env.rb"
Style/Documentation:
  Enabled: false
