inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "integration/**/*"
    - "test/**/*"
    - "node_modules/**/*"
Metrics/ClassLength:
  Enabled: false
Naming/FileName:
  Exclude:
    - "lib/google-cloud-env.rb"
